final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('sign/', include('sign.urls')),
    path('posts/', include('forum.urls')),
]

sign/urls.py
from django.urls import path

from forum.views import PrivatelistView
from .views import profile_view, RegisterView


app_name = 'sign'
urlpatterns = [
   path('profile', profile_view, name="profile"),
   path('register', RegisterView.as_view(), name="register"),

]

templates/layout/parts/footer.html
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

templates/layout/parts/header.html
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="http://127.0.0.1:8000/posts" class="nav-link px-2 text-secondary">Home</a></li>
        <li><a href="{% url 'privatelist' %}" class="nav-link px-2 text-white">Отклик</a></li>
      </ul>

      <div class="text-end">
        <a href="{% url 'login' %}"><button  type="button" class="btn btn-outline-light me-2">Вход</button></a>
        <a href="{% url 'sign:register' %}"><button  type="button" class="btn btn-warning">Регистрация</button></a>
      </div>
    </div>
  </div>
</header>

templates/layout/parts/paginator.html
<!-- Проверяем, что поддерживается постраничный вывод -->
{% if is_paginated %}

   <!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
   {% if page_obj.has_previous %}
       <a href="?page=1">First</a>
       <a href="?page={{ page_obj.previous_page_number }}"> <<< </a>
   {% endif %}

   <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
   {% for num in page_obj.paginator.page_range %}
       {% if page_obj.number == num %}
           <a>{{ num }}</a>
       {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
           <a href="?page={{ num }}">{{ num }}</a>
       {% endif %}
   {% endfor %}

   <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">>>></a>
       <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
   {% endif %}


{% endif %}